### ISSUE TITLE
Provision machines

### ISSUE THREAD

**Issue by poquirion** [c3g/arc#1]
The proxy machine will have the 3 following service

 * NGINX
 * Lets enscrypt 
 * oauth2-proxy

The machine in the back will have 
  * Flask app
  * The postgress database

**Comment by poquirion** [comment]
We could also deply
https://github.com/ansible/awx
To help with issue #3

**Comment by komainu-ctrl** [comment]
Nginx, Let's Encrypt and Oauth2-proxy are install on Dev-SSO-Keycloack

**Comment by poquirion** [comment]
Since we will be using a cmd line cli to talk to the api, some non default config are needed to make the oauth proxy work properly
https://github.com/oauth2-proxy/oauth2-proxy/issues/809
