### ISSUE TITLE
Automatic update of flask app

### ISSUE THREAD

**Issue by poquirion** [c3g/arc#3]

**Comment by poquirion** [comment]
The old version of the app is here. 
https://bitbucket.org/mugqic/moh_automation/src/dev

I first need to package it properly.

**Comment by poquirion** [comment]
This is the app:
https://github.com/c3g/c3g_project_tracking

**Comment by komainu-ctrl** [comment]
Issue who talk about userinfo for flask : 

https://github.com/oauth2-proxy/oauth2-proxy/issues/1842
